### ISSUE TITLE
How do you store decimal like prices?

### ISSUE THREAD

**Issue by divdax** [rinvex/laravel-attributes#104]
I think this package need a new type. Why there is no decimal?
If you want to store e.g. prices, volumes there i cannot use varchar or integer.

**Comment by flakerimi** [comment]
@divdax  if still applicable, PR #119 fix this, or clone my fork

https://github.com/flakerimi/laravel-attributes

**Comment by Omranic** [comment]
The idea of this package is to provide the basic types, and to give you the ability to extend it easily to add your own custom types. You can so that by following the steps here https://github.com/rinvex/laravel-attributes#register-your-types

And here is an example
https://github.com/rinvex/laravel-attributes/pull/119
