### ISSUE TITLE
getEntityAttributes return more than it should

### ISSUE THREAD

**Issue by divdax** [rinvex/laravel-attributes#107]
Given i've two items of `App\Category` with `Attributable` Trait and two attributes where each attribute is assigned to a specific category through `attribute_entity` table with `entity_id`.

Now when i'm trying to get the attribute for the first category with
```php
$category->getEntityAttributes();
```
it will return both attributes, but each category has only one attribute assigned.

Why?

**Comment by divdax** [comment]
@Omranic ?

**Comment by Omranic** [comment]
Thank you for your patience, this is limited by design, and it's difficult to implement the other way. For more details, check this: https://github.com/rinvex/laravel-attributes/blob/5aff4aef8eed44c64c55a13ec1cceabda650d7e9/src/Traits/Attributable.php#L189-L215

However, PRs to add this feature are welcome 🙂
